Update to support S32K JLink scripting.
Origen-SDK/origen_debuggers pull request #1
Opened 2017-03-29 15:18 UTC by redxeth

Minor updates to permit changing the script interfacee method for JLink scripts.  Added support for mem32, q (quit) and halt commands.

2017-03-29 15:33 UTC, ginty requested changes

2017-03-29 15:33 UTC, ginty commented on lib/origen_debuggers/j_link.rb
> +      # Read 32-bit chunks of data using given byte address
Don't really like adding a new method for something like this, better to make the existing read32 method accept a single value or an array of values for the data arg

2017-03-29 15:33 UTC, ginty commented on lib/origen_debuggers/j_link.rb
> +        if options[:type] == :_32
This should be called :size with a numeric arg instead of type (to align to generally used conventions)

2017-03-29 15:35 UTC, redxeth commented on lib/origen_debuggers/j_link.rb
> +        if options[:type] == :_32
There are discrete memXX commands so can't really have user enter anything they want.   But could go numeric and just give error if invalid value.

2017-03-29 15:37 UTC, ginty commented on lib/origen_debuggers/j_link.rb
> +        if options[:type] == :_32
Yes that's fine and would be the conventional way to do it

2017-03-29 15:39 UTC, redxeth commented on lib/origen_debuggers/j_link.rb
> +      # Read 32-bit chunks of data using given byte address
Was trying to get something in there quick -- but can try that.

2017-03-30 07:40 UTC, ginty approved these changes

2017-03-30 14:24 UTC, merged